#!/bin/bash

# Upload to Google Colab Helper Script
# This script helps you prepare files for Google Colab training

echo "=============================================================================="
echo "Google Colab Training Setup Helper"
echo "=============================================================================="
echo ""

# Check if train_pca_colab.ipynb exists
if [ ! -f "train_pca_colab.ipynb" ]; then
    echo "❌ Error: train_pca_colab.ipynb not found!"
    echo "   Make sure you're in the plastic_classification directory"
    exit 1
fi

echo "📋 Files ready for Google Colab:"
echo ""
echo "1. Notebook:"
echo "   ✓ train_pca_colab.ipynb"
echo ""

echo "2. Dataset to upload to Google Drive:"
echo "   ✓ training_dataset/ (all 459 band images + header.json)"
echo "   ✓ Ground_Truth/labels.json"
echo ""

echo "=============================================================================="
echo "STEP-BY-STEP INSTRUCTIONS"
echo "=============================================================================="
echo ""

echo "Step 1: Upload Dataset to Google Drive"
echo "----------------------------------------"
echo "1. Open Google Drive: https://drive.google.com"
echo "2. Create folder: 'plastic_classification'"
echo "3. Upload to this folder:"
echo "   - training_dataset/ (folder with all images)"
echo "   - Ground_Truth/ (folder with labels.json)"
echo ""
echo "Your Drive structure should look like:"
echo "  MyDrive/"
echo "  └── plastic_classification/"
echo "      ├── training_dataset/"
echo "      │   ├── header.json"
echo "      │   ├── ImagesStack001.png"
echo "      │   ├── ImagesStack002.png"
echo "      │   └── ... (all 459 images)"
echo "      └── Ground_Truth/"
echo "          └── labels.json"
echo ""

echo "Step 2: Upload Notebook to Colab"
echo "---------------------------------"
echo "1. Open Google Colab: https://colab.research.google.com"
echo "2. Click 'File' → 'Upload notebook'"
echo "3. Upload 'train_pca_colab.ipynb'"
echo ""
echo "OR"
echo ""
echo "1. Upload train_pca_colab.ipynb to Google Drive"
echo "2. Right-click → 'Open with' → 'Google Colaboratory'"
echo ""

echo "Step 3: Configure Colab Runtime"
echo "--------------------------------"
echo "1. In Colab: Click 'Runtime' → 'Change runtime type'"
echo "2. Select 'GPU' as Hardware accelerator"
echo "3. For Colab Pro+: Choose T4, V100, or A100"
echo "4. Click 'Save'"
echo ""

echo "Step 4: Update Paths in Notebook"
echo "---------------------------------"
echo "1. Find the cell with 'CONFIGURE THESE PATHS'"
echo "2. Update DRIVE_BASE to match your folder:"
echo ""
echo "   DRIVE_BASE = '/content/drive/MyDrive/plastic_classification'"
echo ""
echo "3. Verify paths are correct"
echo ""

echo "Step 5: Run Training"
echo "--------------------"
echo "1. Click 'Runtime' → 'Run all'"
echo "2. Authorize Google Drive access when prompted"
echo "3. Wait for training (~2-3 hours for all configs)"
echo "4. Results will be saved to Google Drive"
echo ""

echo "=============================================================================="
echo "QUICK TEST (Optional)"
echo "=============================================================================="
echo ""
echo "To test with small dataset first (faster):"
echo "1. In the notebook, find CONFIG section"
echo "2. Change settings:"
echo "   'n_epochs': 5,                    # Reduce epochs"
echo "   'max_samples': 10000,             # Use fewer samples"
echo "   'pca_configs': [None, 150],       # Test only 2 configs"
echo "3. Run notebook"
echo "4. If successful, change back to full settings"
echo ""

echo "=============================================================================="
echo "RESULTS LOCATION"
echo "=============================================================================="
echo ""
echo "After training, find results in Google Drive:"
echo ""
echo "  MyDrive/plastic_classification/colab_results/"
echo "  ├── no_pca/"
echo "  │   ├── best_model.pth"
echo "  │   └── history.json"
echo "  ├── pca_150/"
echo "  │   ├── best_model.pth"
echo "  │   ├── pca_model.pkl"
echo "  │   └── history.json"
echo "  ├── comparison_results.json"
echo "  └── comparison_plot.png"
echo ""

echo "=============================================================================="
echo "DOWNLOAD RESULTS"
echo "=============================================================================="
echo ""
echo "Option 1: Auto-download from Colab"
echo "  - Last cell in notebook downloads zip file"
echo ""
echo "Option 2: Manual download from Google Drive"
echo "  - Go to Drive → plastic_classification/colab_results"
echo "  - Right-click → Download"
echo ""

echo "=============================================================================="
echo "NEXT STEPS"
echo "=============================================================================="
echo ""
echo "1. ✅ Upload dataset to Google Drive (training_dataset + Ground_Truth)"
echo "2. ✅ Upload notebook to Colab (train_pca_colab.ipynb)"
echo "3. ✅ Enable GPU runtime in Colab"
echo "4. ✅ Update paths in notebook"
echo "5. ✅ Run all cells"
echo "6. ✅ Download results when complete"
echo ""

echo "For detailed help, see: COLAB_SETUP_GUIDE.md"
echo ""

echo "=============================================================================="
echo "Ready to start? Follow the steps above!"
echo "=============================================================================="
